version: 2
jobs:
  scala-weights-test:
    docker:
        - image: hseeberger/scala-sbt:8u171_2.12.6_1.1.6
    steps:
        - checkout
        - run:
            name: run-scala-tests
            command: |
              cd server
              sbt clean compile
              sbt test
workflows:
  version: 2
  test_all:
    jobs:
      - scala-weights-test
