version: 2
jobs:
  frontend-test:
    docker:
        - image: circleci/node:8.11-browsers
    working_directory: ~/Fe/frontend
    steps:
        - checkout
        # download & cache dependencies
        - run: pwd
        - run: cat ./yarn.lock
        - restore_cache:
            keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no match found
            - dependencies-
        - run: yarn install --pure-lockfile
        - save_cache:
            paths:
              - node_modules
            key: dependencies-{{ checksum "yarn.lock" }}
        - run: yarn lint:js
        - run: yarn
  scala-weights-test:
    docker:
        - image: hseeberger/scala-sbt:8u171_2.12.6_1.1.6
    steps:
        - checkout
        - run:
            name: run-scala-tests
            command: |
              cd server
              sbt clean compile
              sbt test
workflows:
  version: 2
  test_all:
    jobs:
      - scala-weights-test
      - frontend-test

